application: brps
version: 1
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images
 
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /brps.js
  static_files: brps.js
  upload: brps.js

- url: /admin
  script: admin.py
  login: admin

- url: /.*
  script: index.py
